apiVersion: "kubeflow.org/v1alpha1"
kind: StudyJob
metadata:
  namespace: kubeflow
  labels:
    controller-tools.k8s.io: "1.0"
  name: books-recsys-example

spec:
  studyName: books-recsys-example
  owner: crd
  optimizationtype: minimize
  objectivevaluename: mean_squared_error
  optimizationgoal: 0.6
  requestcount: 10

  parameterconfigs:
    - name: --embedding-size
      parametertype: int
      feasible:
        min: "10"
        max: "50"


  workerSpec:
    goTemplate:
      rawTemplate: |-
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: {{.WorkerID}}
          namespace: kubeflow
        spec:
          template:
            # The training worker uses the Ames housing example found at
            # https://github.com/kubeflow/examples/tree/master/xgboost_ames_housing.
            # Please first follow the steps and create the required prerequisites.
            spec:
              containers:
              - name: {{.WorkerID}}
                image: gcr.io/kubeflow-examples/ames-housing:latest
                volumeMounts:
                - mountPath: "/mnt/xgboost"
                  name: datadir
                command:
                - "python"
                - "model.py"
                - "--tf-model-dir=/tmp/model_{{.WorkerID}}"
                - "--tf-export-dir=/tmp/export_{{.WorkerID}}"
                {{- with .HyperParameters}}
                {{- range .}}
                - "{{.Name}}={{.Value}}"
                {{- end}}
                {{- end}}
              volumes:
              - name: datadir
                persistentVolumeClaim:
                claimName: claim
              restartPolicy: Never

  suggestionSpec:
    suggestionAlgorithm: "bayesianoptimization"
    suggestionParameters:
      -
          name: "burn_in"
          value: "5"
    requestNumber: 10